version: '3.8'

services:

    nodeserver:
        build:
            # context tells docker-compose the path to find the Dockerfile for this service.
            context: ./app
        ports:
            # port mapping from the local machine to a port inside the Docker container.
            - '5000:5000'

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            # if we visit http://localhost:8080 on our browser, we are viewing whatever is being hosted on 
            # the port 80 inside the container. Nginx image listens on port 80 by default.
            - '8080:80'